name: finance

services:
  finance-api:
    image: dpereira99/finance-api:latest
    container_name: finance-api
    build: .
    ports:
      - 8001:80
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    networks:
      finance:
  finance-app:
    image: dpereira99/finance-app:latest
    container_name: finance-app
    build: ../finance-app/
    ports:
      - 8002:8000
    environment:
      DB_ENGINE: ${DB_ENGINE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      API_HOST: ${API_HOST}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      finance:
    depends_on:
      - finance-api

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

networks:
  finance:
    driver: bridge
