services:
  finance-api:
    image: dpereira99/finance-api:latest
    container_name: finance-api
    build: .
    ports:
      - 8001:80
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    networks:
      finance:
        ipv4_address: 172.19.0.3

  finance-app:
    image: dpereira99/finance-app:latest
    container_name: finance-app
    build: ../finance-app/
    ports:
      - 8002:8000
    networks:
      finance:
        ipv4_address: 172.19.0.2
    depends_on:
     - finance-api

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 finance-app | --interval 30 finance-api

networks:
  finance:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1